export type ProposalStatus = "Active" | "Accepted" | "Rejected" | "Finished";

export interface Discussion {
  id: string;
  author: string;
  avatar: string;
  message: string;
  timestamp: string;
}

export interface TopVoter {
  address: string;
  displayName: string;
  vote: "FOR" | "AGAINST";
  amount: number;
  avatar: string;
}

export interface Proposal {
  id: string;
  title: string;
  author: string;
  authorAvatar: string;
  summary: string;
  motivation: string;
  specification: string;
  status: ProposalStatus;
  forVotes: number;
  forPct: number;
  againstVotes: number;
  againstPct: number;
  abstainVotes: number;
  abstainPct: number;
  token: string;
  quorum: number;
  quorumRequired: number;
  differential: number;
  differentialRequired: number;
  topVoters: TopVoter[];
  discussions: Discussion[];
}

const AVATARS = [
  "https://api.dicebear.com/7.x/avataaars/svg?seed=mezocore",
  "https://api.dicebear.com/7.x/avataaars/svg?seed=defiwhale",
  "https://api.dicebear.com/7.x/avataaars/svg?seed=btcmaxi",
  "https://api.dicebear.com/7.x/avataaars/svg?seed=ethmaxi",
  "https://api.dicebear.com/7.x/avataaars/svg?seed=tokenlogic",
  "https://api.dicebear.com/7.x/avataaars/svg?seed=secteam",
  "https://api.dicebear.com/7.x/avataaars/svg?seed=grantcouncil",
  "https://api.dicebear.com/7.x/avataaars/svg?seed=riskteam",
  "https://api.dicebear.com/7.x/avataaars/svg?seed=chainlink",
  "https://api.dicebear.com/7.x/avataaars/svg?seed=mezolabs",
];

function avatar(seed: string) {
  return `https://api.dicebear.com/7.x/avataaars/svg?seed=${seed}`;
}

export const proposals: Proposal[] = [
  {
    id: "MIP-045",
    title: "Increase BTC collateral ratio to 150% for enhanced protocol safety",
    author: "Mezo Core (@mezocore)",
    authorAvatar: avatar("mezocore"),
    summary: "This proposal increases the BTC collateral ratio from 130% to 150% to provide additional safety margins during periods of high volatility, protecting MUSD peg stability.",
    motivation: "Following recent market turbulence and liquidation cascades across DeFi protocols, it has become clear that a higher collateral ratio is needed to ensure the protocol can withstand extreme volatility. The current 130% ratio, while functional under normal conditions, leaves insufficient margin during black swan events. By increasing to 150%, we provide a larger buffer that protects both borrowers and the MUSD peg.",
    specification: "Update the BTC collateral ratio parameter in the Mezo Vault contract from 130% to 150%. This change affects new positions only — existing positions will be grandfathered at the current ratio for a 30-day migration period. The liquidation threshold will be adjusted accordingly from 115% to 125%.",
    status: "Active",
    forVotes: 245000,
    forPct: 87.3,
    againstVotes: 35600,
    againstPct: 12.7,
    abstainVotes: 4200,
    abstainPct: 1.5,
    token: "MEZO",
    quorum: 280600,
    quorumRequired: 200000,
    differential: 209400,
    differentialRequired: 80000,
    topVoters: [
      { address: "0xae3f...c4d2", displayName: "mezocore.eth", vote: "FOR", amount: 89200, avatar: avatar("mezocore") },
      { address: "0x12ab...9f31", displayName: "defiwhale.eth", vote: "FOR", amount: 52100, avatar: avatar("defiwhale") },
      { address: "0x8c4e...a1b7", displayName: "0x8c4e...a1b7", vote: "FOR", amount: 34500, avatar: avatar("user3") },
      { address: "0xf291...3e8c", displayName: "btcmaxi.eth", vote: "AGAINST", amount: 21300, avatar: avatar("btcmaxi") },
      { address: "0x5d7a...b2f0", displayName: "0x5d7a...b2f0", vote: "FOR", amount: 18900, avatar: avatar("user5") },
    ],
    discussions: [
      { id: "d1", author: "mezocore.eth", avatar: avatar("mezocore"), message: "This is critical for protocol safety. The recent market events showed our current ratio is too thin.", timestamp: "2 days ago" },
      { id: "d2", author: "btcmaxi.eth", avatar: avatar("btcmaxi"), message: "I'm concerned this will reduce capital efficiency. Can we consider 140% as a compromise?", timestamp: "1 day ago" },
      { id: "d3", author: "defiwhale.eth", avatar: avatar("defiwhale"), message: "Safety first. 150% is the right call given current market conditions.", timestamp: "12 hours ago" },
    ],
  },
  {
    id: "MIP-044",
    title: "Add wstETH as collateral asset on Mezo",
    author: "DeFi Committee (@deficommittee)",
    authorAvatar: avatar("deficommittee"),
    summary: "Proposal to add Lido's wrapped staked ETH (wstETH) as an accepted collateral type, expanding the range of assets that can back MUSD minting.",
    motivation: "Expanding collateral types beyond BTC increases protocol utility and attracts a broader user base. wstETH is a battle-tested, yield-bearing asset with deep liquidity and robust price feeds.",
    specification: "Deploy a new wstETH Vault contract with initial parameters: collateral ratio 160%, liquidation threshold 135%, stability fee 2.5% APR. Integrate Chainlink wstETH/USD price feed. Set initial debt ceiling at 5M MUSD.",
    status: "Accepted",
    forVotes: 373000,
    forPct: 100,
    againstVotes: 0,
    againstPct: 0,
    abstainVotes: 0,
    abstainPct: 0,
    token: "MEZO",
    quorum: 373000,
    quorumRequired: 200000,
    differential: 373000,
    differentialRequired: 80000,
    topVoters: [
      { address: "0xae3f...c4d2", displayName: "mezocore.eth", vote: "FOR", amount: 112000, avatar: avatar("mezocore") },
      { address: "0x7b2c...d4e1", displayName: "lidodao.eth", vote: "FOR", amount: 87500, avatar: avatar("lidodao") },
      { address: "0x12ab...9f31", displayName: "defiwhale.eth", vote: "FOR", amount: 65200, avatar: avatar("defiwhale") },
      { address: "0x3f8e...c2a9", displayName: "0x3f8e...c2a9", vote: "FOR", amount: 41800, avatar: avatar("user4") },
      { address: "0x9d1b...7f3e", displayName: "ethmaxi.eth", vote: "FOR", amount: 33200, avatar: avatar("ethmaxi") },
    ],
    discussions: [
      { id: "d1", author: "lidodao.eth", avatar: avatar("lidodao"), message: "Excited to see wstETH integration! Happy to help with technical implementation.", timestamp: "5 days ago" },
      { id: "d2", author: "defiwhale.eth", avatar: avatar("defiwhale"), message: "Strong support. This expands Mezo's TAM significantly.", timestamp: "4 days ago" },
    ],
  },
  {
    id: "MIP-043",
    title: "Treasury allocation for Q2 ecosystem grants program",
    author: "Grants Council (@grantcouncil)",
    authorAvatar: avatar("grantcouncil"),
    summary: "Allocate 2M MEZO from the community treasury to fund Q2 ecosystem grants, supporting developer tooling, integrations, and community initiatives.",
    motivation: "The Q1 grants program successfully funded 12 projects that contributed to protocol growth, including 3 new integrations and 5 developer tools.",
    specification: "Transfer 2,000,000 MEZO from the Community Treasury multisig to the Grants Council multisig (0x7a2b...e4f1). Funds to be distributed across 4 categories: Developer Tooling (800K), Integrations (500K), Community Initiatives (400K), Security Audits (300K).",
    status: "Finished",
    forVotes: 559000,
    forPct: 100,
    againstVotes: 0,
    againstPct: 0,
    abstainVotes: 0,
    abstainPct: 0,
    token: "MEZO",
    quorum: 559000,
    quorumRequired: 200000,
    differential: 559000,
    differentialRequired: 80000,
    topVoters: [
      { address: "0xae3f...c4d2", displayName: "mezocore.eth", vote: "FOR", amount: 156000, avatar: avatar("mezocore") },
      { address: "0x12ab...9f31", displayName: "defiwhale.eth", vote: "FOR", amount: 98700, avatar: avatar("defiwhale") },
      { address: "0x7b2c...d4e1", displayName: "grantcouncil.eth", vote: "FOR", amount: 75000, avatar: avatar("grantcouncil") },
      { address: "0x5d7a...b2f0", displayName: "0x5d7a...b2f0", vote: "FOR", amount: 62400, avatar: avatar("user5") },
      { address: "0x8c4e...a1b7", displayName: "0x8c4e...a1b7", vote: "FOR", amount: 48300, avatar: avatar("user3") },
    ],
    discussions: [
      { id: "d1", author: "grantcouncil.eth", avatar: avatar("grantcouncil"), message: "Q1 results were excellent. We expect even better outcomes in Q2 with the expanded program.", timestamp: "1 week ago" },
    ],
  },
  {
    id: "MIP-042",
    title: "Reduce protocol swap fees from 0.30% to 0.25%",
    author: "TokenLogic (@tokenlogic)",
    authorAvatar: avatar("tokenlogic"),
    summary: "Lower the base swap fee on the MUSD/BTC pool to increase volume and competitiveness against other DEX protocols on Mezo.",
    motivation: "Competitive analysis shows that rival DEXs on Mezo are offering swap fees as low as 0.20%. Our current 0.30% fee is resulting in volume leakage.",
    specification: "Update the swapFee parameter on the MUSD/BTC Pool contract from 30 bps to 25 bps. This change takes effect immediately upon execution. Monitor volume metrics for 30 days.",
    status: "Active",
    forVotes: 189000,
    forPct: 73.5,
    againstVotes: 68200,
    againstPct: 26.5,
    abstainVotes: 5400,
    abstainPct: 2.1,
    token: "MEZO",
    quorum: 257200,
    quorumRequired: 200000,
    differential: 120800,
    differentialRequired: 80000,
    topVoters: [
      { address: "0x3f8e...c2a9", displayName: "tokenlogic.eth", vote: "FOR", amount: 64000, avatar: avatar("tokenlogic") },
      { address: "0xf291...3e8c", displayName: "btcmaxi.eth", vote: "AGAINST", amount: 45200, avatar: avatar("btcmaxi") },
      { address: "0x12ab...9f31", displayName: "defiwhale.eth", vote: "FOR", amount: 38700, avatar: avatar("defiwhale") },
      { address: "0x9d1b...7f3e", displayName: "0x9d1b...7f3e", vote: "AGAINST", amount: 23000, avatar: avatar("user6") },
      { address: "0xae3f...c4d2", displayName: "mezocore.eth", vote: "FOR", amount: 19800, avatar: avatar("mezocore") },
    ],
    discussions: [
      { id: "d1", author: "tokenlogic.eth", avatar: avatar("tokenlogic"), message: "Our analysis shows 0.25% is the sweet spot for maximizing volume while maintaining revenue.", timestamp: "3 days ago" },
      { id: "d2", author: "btcmaxi.eth", avatar: avatar("btcmaxi"), message: "Reducing fees will hurt protocol revenue. We should focus on adding value, not cutting prices.", timestamp: "2 days ago" },
    ],
  },
  {
    id: "MIP-041",
    title: "Deploy Mezo Gauge Controller v2 with veBoost integration",
    author: "Mezo Labs (@mezolabs)",
    authorAvatar: avatar("mezolabs"),
    summary: "Upgrade the gauge controller to v2 which integrates veBoost mechanics, allowing veMEZO lockers to receive amplified gauge voting power.",
    motivation: "The current gauge controller lacks incentive alignment between long-term lockers and short-term participants.",
    specification: "Deploy GaugeControllerV2 contract with veBoost multipliers: 1 year lock = 1x, 2 years = 1.5x, 3 years = 2x, 4 years = 3x boost. Migrate all existing gauge weights.",
    status: "Accepted",
    forVotes: 412000,
    forPct: 96.8,
    againstVotes: 13600,
    againstPct: 3.2,
    abstainVotes: 2100,
    abstainPct: 0.5,
    token: "MEZO",
    quorum: 425600,
    quorumRequired: 200000,
    differential: 398400,
    differentialRequired: 80000,
    topVoters: [
      { address: "0xae3f...c4d2", displayName: "mezolabs.eth", vote: "FOR", amount: 134000, avatar: avatar("mezolabs") },
      { address: "0x12ab...9f31", displayName: "defiwhale.eth", vote: "FOR", amount: 89300, avatar: avatar("defiwhale") },
      { address: "0x7b2c...d4e1", displayName: "0x7b2c...d4e1", vote: "FOR", amount: 56700, avatar: avatar("user7") },
      { address: "0x5d7a...b2f0", displayName: "0x5d7a...b2f0", vote: "FOR", amount: 42100, avatar: avatar("user5") },
      { address: "0xf291...3e8c", displayName: "btcmaxi.eth", vote: "AGAINST", amount: 13600, avatar: avatar("btcmaxi") },
    ],
    discussions: [
      { id: "d1", author: "mezolabs.eth", avatar: avatar("mezolabs"), message: "veBoost is essential for aligning long-term holders with protocol health.", timestamp: "1 week ago" },
    ],
  },
  {
    id: "MIP-040",
    title: "Emergency parameter adjustment for MUSD stability module",
    author: "Risk Team (@riskteam)",
    authorAvatar: avatar("riskteam"),
    summary: "Emergency proposal to adjust the MUSD Peg Stability Module parameters in response to recent market conditions.",
    motivation: "Over the past 72 hours, MUSD has traded at a persistent discount of 0.3-0.5% below peg due to a large redemption event.",
    specification: "Update PSM parameters: reduce mint fee from 0.1% to 0.05%, increase redemption fee from 0.1% to 0.15%, increase PSM buffer from 1M MUSD to 3M MUSD.",
    status: "Rejected",
    forVotes: 98000,
    forPct: 34.2,
    againstVotes: 188500,
    againstPct: 65.8,
    abstainVotes: 8300,
    abstainPct: 2.9,
    token: "MEZO",
    quorum: 286500,
    quorumRequired: 200000,
    differential: 90500,
    differentialRequired: 80000,
    topVoters: [
      { address: "0xf291...3e8c", displayName: "btcmaxi.eth", vote: "AGAINST", amount: 78200, avatar: avatar("btcmaxi") },
      { address: "0x9d1b...7f3e", displayName: "0x9d1b...7f3e", vote: "AGAINST", amount: 54300, avatar: avatar("user6") },
      { address: "0xae3f...c4d2", displayName: "riskteam.eth", vote: "FOR", amount: 45000, avatar: avatar("riskteam") },
      { address: "0x12ab...9f31", displayName: "defiwhale.eth", vote: "AGAINST", amount: 38900, avatar: avatar("defiwhale") },
      { address: "0x3f8e...c2a9", displayName: "0x3f8e...c2a9", vote: "FOR", amount: 28700, avatar: avatar("user4") },
    ],
    discussions: [
      { id: "d1", author: "riskteam.eth", avatar: avatar("riskteam"), message: "We need to act fast to restore the peg. These parameters are carefully calibrated.", timestamp: "4 days ago" },
      { id: "d2", author: "btcmaxi.eth", avatar: avatar("btcmaxi"), message: "Emergency proposals should not be used for parameter changes that can wait for normal governance.", timestamp: "3 days ago" },
      { id: "d3", author: "defiwhale.eth", avatar: avatar("defiwhale"), message: "The peg is already recovering naturally. No need for emergency action.", timestamp: "3 days ago" },
    ],
  },
  {
    id: "MIP-039",
    title: "Integrate Chainlink CCIP for cross-chain MUSD transfers",
    author: "Mezo Labs (@mezolabs)",
    authorAvatar: avatar("mezolabs"),
    summary: "Enable cross-chain MUSD transfers using Chainlink's Cross-Chain Interoperability Protocol (CCIP).",
    motivation: "MUSD is currently confined to the Mezo network. By integrating Chainlink CCIP, we can enable seamless cross-chain transfers.",
    specification: "Deploy CCIP-compatible MUSD bridge contracts on Mezo, Ethereum, Arbitrum, and Base. Implement burn-and-mint mechanism with rate limiting.",
    status: "Active",
    forVotes: 312000,
    forPct: 91.2,
    againstVotes: 30100,
    againstPct: 8.8,
    abstainVotes: 3200,
    abstainPct: 0.9,
    token: "MEZO",
    quorum: 342100,
    quorumRequired: 200000,
    differential: 281900,
    differentialRequired: 80000,
    topVoters: [
      { address: "0xae3f...c4d2", displayName: "mezolabs.eth", vote: "FOR", amount: 95000, avatar: avatar("mezolabs") },
      { address: "0x12ab...9f31", displayName: "defiwhale.eth", vote: "FOR", amount: 72400, avatar: avatar("defiwhale") },
      { address: "0x7b2c...d4e1", displayName: "chainlink.eth", vote: "FOR", amount: 58300, avatar: avatar("chainlink") },
      { address: "0xf291...3e8c", displayName: "btcmaxi.eth", vote: "AGAINST", amount: 22100, avatar: avatar("btcmaxi") },
      { address: "0x5d7a...b2f0", displayName: "0x5d7a...b2f0", vote: "FOR", amount: 19800, avatar: avatar("user5") },
    ],
    discussions: [
      { id: "d1", author: "chainlink.eth", avatar: avatar("chainlink"), message: "We're ready to support Mezo's CCIP integration. Technical specs have been shared with the team.", timestamp: "6 days ago" },
    ],
  },
  {
    id: "MIP-038",
    title: "Launch MEZO Staking Rewards program with 8% APY",
    author: "Rewards Committee (@rewardscommittee)",
    authorAvatar: avatar("rewardscommittee"),
    summary: "Introduce a staking rewards program offering 8% APY for MEZO stakers.",
    motivation: "Currently there is no direct incentive for MEZO holders to stake and participate in governance beyond voting rights.",
    specification: "Deploy StakingRewards contract with 8% APY funded from protocol revenue. Minimum stake: 100 MEZO. No lock-up period but 7-day cooldown on unstaking.",
    status: "Accepted",
    forVotes: 487000,
    forPct: 94.5,
    againstVotes: 28300,
    againstPct: 5.5,
    abstainVotes: 1500,
    abstainPct: 0.3,
    token: "MEZO",
    quorum: 515300,
    quorumRequired: 200000,
    differential: 458700,
    differentialRequired: 80000,
    topVoters: [
      { address: "0xae3f...c4d2", displayName: "mezocore.eth", vote: "FOR", amount: 142000, avatar: avatar("mezocore") },
      { address: "0x12ab...9f31", displayName: "defiwhale.eth", vote: "FOR", amount: 105000, avatar: avatar("defiwhale") },
      { address: "0x3f8e...c2a9", displayName: "0x3f8e...c2a9", vote: "FOR", amount: 68700, avatar: avatar("user4") },
      { address: "0x9d1b...7f3e", displayName: "ethmaxi.eth", vote: "FOR", amount: 45200, avatar: avatar("ethmaxi") },
      { address: "0xf291...3e8c", displayName: "btcmaxi.eth", vote: "AGAINST", amount: 28300, avatar: avatar("btcmaxi") },
    ],
    discussions: [
      { id: "d1", author: "mezocore.eth", avatar: avatar("mezocore"), message: "8% APY is sustainable from current protocol revenue. This will drive participation.", timestamp: "2 weeks ago" },
    ],
  },
  {
    id: "MIP-037",
    title: "Establish Mezo Security Council with multisig emergency powers",
    author: "Security Team (@securityteam)",
    authorAvatar: avatar("secteam"),
    summary: "Create a 5-of-9 Security Council multisig with emergency pause capabilities.",
    motivation: "Recent exploits across DeFi have demonstrated the need for rapid response capabilities.",
    specification: "Deploy SecurityCouncil multisig (5-of-9 threshold) with emergency pause functionality on all core protocol contracts.",
    status: "Finished",
    forVotes: 621000,
    forPct: 98.1,
    againstVotes: 12000,
    againstPct: 1.9,
    abstainVotes: 800,
    abstainPct: 0.1,
    token: "MEZO",
    quorum: 633000,
    quorumRequired: 200000,
    differential: 609000,
    differentialRequired: 80000,
    topVoters: [
      { address: "0xae3f...c4d2", displayName: "mezocore.eth", vote: "FOR", amount: 178000, avatar: avatar("mezocore") },
      { address: "0x12ab...9f31", displayName: "defiwhale.eth", vote: "FOR", amount: 112000, avatar: avatar("defiwhale") },
      { address: "0x7b2c...d4e1", displayName: "securityteam.eth", vote: "FOR", amount: 89500, avatar: avatar("secteam") },
      { address: "0x5d7a...b2f0", displayName: "0x5d7a...b2f0", vote: "FOR", amount: 67300, avatar: avatar("user5") },
      { address: "0x8c4e...a1b7", displayName: "0x8c4e...a1b7", vote: "FOR", amount: 52100, avatar: avatar("user3") },
    ],
    discussions: [
      { id: "d1", author: "securityteam.eth", avatar: avatar("secteam"), message: "This is a critical safety measure. The council composition ensures decentralization.", timestamp: "3 weeks ago" },
    ],
  },
  {
    id: "MIP-036",
    title: "Introduce dynamic interest rates for MUSD borrowing",
    author: "DeFi Committee (@deficommittee)",
    authorAvatar: avatar("deficommittee"),
    summary: "Replace the fixed 3% stability fee with a dynamic interest rate model.",
    motivation: "The current fixed 3% stability fee does not respond to market dynamics.",
    specification: "Deploy DynamicRateController with base rate 1.5%, slope1 4% (up to 80% utilization), slope2 75% (above 80% utilization).",
    status: "Active",
    forVotes: 156000,
    forPct: 62.4,
    againstVotes: 94000,
    againstPct: 37.6,
    abstainVotes: 12000,
    abstainPct: 4.6,
    token: "MEZO",
    quorum: 250000,
    quorumRequired: 200000,
    differential: 62000,
    differentialRequired: 80000,
    topVoters: [
      { address: "0x3f8e...c2a9", displayName: "deficommittee.eth", vote: "FOR", amount: 52000, avatar: avatar("deficommittee") },
      { address: "0xf291...3e8c", displayName: "btcmaxi.eth", vote: "AGAINST", amount: 48700, avatar: avatar("btcmaxi") },
      { address: "0x9d1b...7f3e", displayName: "0x9d1b...7f3e", vote: "AGAINST", amount: 31200, avatar: avatar("user6") },
      { address: "0x12ab...9f31", displayName: "defiwhale.eth", vote: "FOR", amount: 38500, avatar: avatar("defiwhale") },
      { address: "0xae3f...c4d2", displayName: "mezocore.eth", vote: "FOR", amount: 27800, avatar: avatar("mezocore") },
    ],
    discussions: [
      { id: "d1", author: "deficommittee.eth", avatar: avatar("deficommittee"), message: "Dynamic rates are proven in DeFi. This will optimize capital efficiency significantly.", timestamp: "5 days ago" },
      { id: "d2", author: "btcmaxi.eth", avatar: avatar("btcmaxi"), message: "Too complex. Fixed rates provide predictability that borrowers need.", timestamp: "4 days ago" },
    ],
  },
  {
    id: "MIP-035",
    title: "Allocate 500K MEZO for bug bounty program expansion",
    author: "Security Team (@securityteam)",
    authorAvatar: avatar("secteam"),
    summary: "Expand the existing bug bounty program with an additional 500K MEZO allocation.",
    motivation: "The current bug bounty program has a remaining budget of only 50K MEZO, insufficient to attract top-tier security researchers.",
    specification: "Transfer 500,000 MEZO from Community Treasury to Bug Bounty multisig. Bounty tiers: Critical = 100K MEZO, High = 25K MEZO, Medium = 5K MEZO, Low = 1K MEZO.",
    status: "Accepted",
    forVotes: 534000,
    forPct: 99.3,
    againstVotes: 3800,
    againstPct: 0.7,
    abstainVotes: 500,
    abstainPct: 0.1,
    token: "MEZO",
    quorum: 537800,
    quorumRequired: 200000,
    differential: 530200,
    differentialRequired: 80000,
    topVoters: [
      { address: "0xae3f...c4d2", displayName: "mezocore.eth", vote: "FOR", amount: 165000, avatar: avatar("mezocore") },
      { address: "0x12ab...9f31", displayName: "defiwhale.eth", vote: "FOR", amount: 98000, avatar: avatar("defiwhale") },
      { address: "0x7b2c...d4e1", displayName: "securityteam.eth", vote: "FOR", amount: 82400, avatar: avatar("secteam") },
      { address: "0x5d7a...b2f0", displayName: "0x5d7a...b2f0", vote: "FOR", amount: 54300, avatar: avatar("user5") },
      { address: "0x3f8e...c2a9", displayName: "0x3f8e...c2a9", vote: "FOR", amount: 41200, avatar: avatar("user4") },
    ],
    discussions: [
      { id: "d1", author: "securityteam.eth", avatar: avatar("secteam"), message: "Security is paramount. This investment pays for itself by preventing exploits.", timestamp: "2 weeks ago" },
    ],
  },
  {
    id: "MIP-034",
    title: "Implement MUSD flash loan module for arbitrage and liquidation",
    author: "Mezo Labs (@mezolabs)",
    authorAvatar: avatar("mezolabs"),
    summary: "Add a flash loan module allowing uncollateralized MUSD borrowing within a single transaction for arbitrage and liquidation use cases.",
    motivation: "Flash loans are a proven DeFi primitive that increase capital efficiency and improve liquidation speed across the protocol.",
    specification: "Deploy FlashLoanModule with 0.05% fee, max loan 10M MUSD per tx. Integrate with existing Vault and PSM contracts.",
    status: "Active",
    forVotes: 198000,
    forPct: 78.1,
    againstVotes: 55600,
    againstPct: 21.9,
    abstainVotes: 3100,
    abstainPct: 1.2,
    token: "MEZO",
    quorum: 253600,
    quorumRequired: 200000,
    differential: 142400,
    differentialRequired: 80000,
    topVoters: [
      { address: "0xae3f...c4d2", displayName: "mezolabs.eth", vote: "FOR", amount: 72000, avatar: avatar("mezolabs") },
      { address: "0x12ab...9f31", displayName: "defiwhale.eth", vote: "FOR", amount: 48000, avatar: avatar("defiwhale") },
      { address: "0xf291...3e8c", displayName: "btcmaxi.eth", vote: "AGAINST", amount: 35600, avatar: avatar("btcmaxi") },
    ],
    discussions: [
      { id: "d1", author: "mezolabs.eth", avatar: avatar("mezolabs"), message: "Flash loans will significantly improve liquidation efficiency.", timestamp: "1 day ago" },
    ],
  },
  {
    id: "MIP-033",
    title: "Enable multi-collateral vaults with weighted basket support",
    author: "TokenLogic (@tokenlogic)",
    authorAvatar: avatar("tokenlogic"),
    summary: "Allow users to deposit multiple collateral types in a single vault with weighted basket valuation.",
    motivation: "Single-collateral vaults limit capital efficiency. Multi-collateral baskets allow better risk distribution.",
    specification: "Deploy MultiCollateralVault supporting up to 5 asset types per vault. Weighted average collateral ratio based on individual asset risk parameters.",
    status: "Rejected",
    forVotes: 112000,
    forPct: 41.3,
    againstVotes: 159000,
    againstPct: 58.7,
    abstainVotes: 7200,
    abstainPct: 2.6,
    token: "MEZO",
    quorum: 271000,
    quorumRequired: 200000,
    differential: 47000,
    differentialRequired: 80000,
    topVoters: [
      { address: "0x3f8e...c2a9", displayName: "tokenlogic.eth", vote: "FOR", amount: 45000, avatar: avatar("tokenlogic") },
      { address: "0xf291...3e8c", displayName: "btcmaxi.eth", vote: "AGAINST", amount: 62000, avatar: avatar("btcmaxi") },
      { address: "0x12ab...9f31", displayName: "defiwhale.eth", vote: "AGAINST", amount: 41000, avatar: avatar("defiwhale") },
    ],
    discussions: [
      { id: "d1", author: "btcmaxi.eth", avatar: avatar("btcmaxi"), message: "Multi-collateral adds systemic risk. Keep it simple.", timestamp: "1 week ago" },
    ],
  },
  {
    id: "MIP-032",
    title: "Launch Mezo Rewards NFT program for governance participation",
    author: "Rewards Committee (@rewardscommittee)",
    authorAvatar: avatar("rewardscommittee"),
    summary: "Introduce NFT badges that reward consistent governance participation with tiered benefits.",
    motivation: "Governance participation rates have declined 15% over Q1. NFT badges provide social proof and tangible rewards for active voters.",
    specification: "Deploy GovernanceNFT contract: Bronze (5+ votes), Silver (20+ votes), Gold (50+ votes). Each tier unlocks fee discounts and boosted voting weight.",
    status: "Finished",
    forVotes: 445000,
    forPct: 93.7,
    againstVotes: 30000,
    againstPct: 6.3,
    abstainVotes: 2000,
    abstainPct: 0.4,
    token: "MEZO",
    quorum: 475000,
    quorumRequired: 200000,
    differential: 415000,
    differentialRequired: 80000,
    topVoters: [
      { address: "0xae3f...c4d2", displayName: "mezocore.eth", vote: "FOR", amount: 130000, avatar: avatar("mezocore") },
      { address: "0x12ab...9f31", displayName: "defiwhale.eth", vote: "FOR", amount: 95000, avatar: avatar("defiwhale") },
      { address: "0x5d7a...b2f0", displayName: "0x5d7a...b2f0", vote: "FOR", amount: 58000, avatar: avatar("user5") },
    ],
    discussions: [
      { id: "d1", author: "rewardscommittee.eth", avatar: avatar("rewardscommittee"), message: "NFTs drive engagement. This has worked well in other protocols.", timestamp: "2 weeks ago" },
    ],
  },
  {
    id: "MIP-031",
    title: "Reduce governance proposal quorum from 200K to 150K MEZO",
    author: "Mezo Core (@mezocore)",
    authorAvatar: avatar("mezocore"),
    summary: "Lower the quorum threshold to increase governance throughput and reduce proposal bottlenecks.",
    motivation: "Several important proposals have failed to reach quorum despite strong community support, creating governance deadlock.",
    specification: "Update quorumVotes parameter in GovernorBravo from 200,000 MEZO to 150,000 MEZO. Apply to all new proposals immediately.",
    status: "Active",
    forVotes: 167000,
    forPct: 69.6,
    againstVotes: 73000,
    againstPct: 30.4,
    abstainVotes: 8500,
    abstainPct: 3.4,
    token: "MEZO",
    quorum: 240000,
    quorumRequired: 200000,
    differential: 94000,
    differentialRequired: 80000,
    topVoters: [
      { address: "0xae3f...c4d2", displayName: "mezocore.eth", vote: "FOR", amount: 58000, avatar: avatar("mezocore") },
      { address: "0xf291...3e8c", displayName: "btcmaxi.eth", vote: "AGAINST", amount: 42000, avatar: avatar("btcmaxi") },
      { address: "0x12ab...9f31", displayName: "defiwhale.eth", vote: "FOR", amount: 39000, avatar: avatar("defiwhale") },
    ],
    discussions: [
      { id: "d1", author: "mezocore.eth", avatar: avatar("mezocore"), message: "We need to make governance more accessible. 200K is too high.", timestamp: "2 days ago" },
      { id: "d2", author: "btcmaxi.eth", avatar: avatar("btcmaxi"), message: "Lowering quorum weakens governance security. If proposals can't reach quorum they shouldn't pass.", timestamp: "1 day ago" },
    ],
  },
  {
    id: "MIP-030",
    title: "Deploy Mezo Protocol Insurance Fund with 1M MUSD seed",
    author: "Risk Team (@riskteam)",
    authorAvatar: avatar("riskteam"),
    summary: "Create a protocol insurance fund to cover potential losses from exploits or black swan events.",
    motivation: "No protocol-level insurance exists. The fund provides a backstop for users in case of unexpected losses.",
    specification: "Deploy InsuranceFund contract seeded with 1,000,000 MUSD. Fund grows via 10% of protocol revenue allocation. Claims require Security Council approval.",
    status: "Accepted",
    forVotes: 498000,
    forPct: 95.4,
    againstVotes: 24000,
    againstPct: 4.6,
    abstainVotes: 1800,
    abstainPct: 0.3,
    token: "MEZO",
    quorum: 522000,
    quorumRequired: 200000,
    differential: 474000,
    differentialRequired: 80000,
    topVoters: [
      { address: "0xae3f...c4d2", displayName: "riskteam.eth", vote: "FOR", amount: 145000, avatar: avatar("riskteam") },
      { address: "0x12ab...9f31", displayName: "defiwhale.eth", vote: "FOR", amount: 108000, avatar: avatar("defiwhale") },
      { address: "0x7b2c...d4e1", displayName: "securityteam.eth", vote: "FOR", amount: 76000, avatar: avatar("secteam") },
    ],
    discussions: [
      { id: "d1", author: "riskteam.eth", avatar: avatar("riskteam"), message: "Insurance is table stakes for mature DeFi protocols.", timestamp: "10 days ago" },
    ],
  },
PLACEHOLDER_NEW_PROPOSALS
];

export const statusStyles: Record<ProposalStatus, string> = {
  "Active": "border-blue-500/40 text-blue-500 bg-blue-500/5",
  "Accepted": "border-emerald-500/40 text-emerald-600 bg-emerald-500/5",
  "Rejected": "border-destructive/40 text-destructive bg-destructive/5",
  "Finished": "border-muted-foreground/40 text-muted-foreground bg-muted/50",
};

export function formatVotes(n: number): string {
  if (n >= 1000) return `${(n / 1000).toFixed(1).replace(/\.0$/, "")}K`;
  return n.toString();
}

// Fee & contract constants
export const VOTING_FEE = "0.2"; // 0.2 token fee per vote
export const MEZO_TOKEN = "0x7B7c000000000000000000000000000000000001" as `0x${string}`;
export const MUSD_TOKEN = "0x94FF830F078eb9c6e77bADe29FB46B1a249A5fd3" as `0x${string}`;
